/** tile heights per second */
export const TILE_FALL_SPEED = 10
export const MIN_TILE_FALL_DURATION_MS = 10
export const TILE_BOUNCE_DURATION_MS = 150
export const TILE_BOUNCE_HEIGHT_RATIO = 0.05
export const TILE_APPEAR_DURATION_MS = 150
export const TILE_REMOVE_DURATION_MS = 150
export const TILE_DELAY_BETWEEN_REMOVALS_MS = TILE_REMOVE_DURATION_MS / 4
export const TILE_SHUFFLE_DURATION_MS = 900
